branch-defaults:
  rds-database:
    environment: null
    group_suffix: null
global:
  application_name: Wordbank
  branch: null
  default_platform: Python 3.8
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: wordbank
  repository: null
  sc: git
  workspace_type: Application
