# Generated by Django 3.1.7 on 2021-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='study_id',
            field=models.CharField(max_length=201, null=True),
        ),
    ]
