# Generated by Django 3.1.7 on 2021-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='name',
            field=models.CharField(max_length=251, primary_key=True, serialize=False),
        ),
    ]
