# Generated by Django 3.1.14 on 2023-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_squashed_0004_auto_20220923_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='date_format',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='file_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='norming',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='splitcol',
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
    ]
