# Generated by Django 3.1.7 on 2021-05-31 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210503_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languageexposure',
            name='language_days_per_week',
        ),
        migrations.RemoveField(
            model_name='languageexposure',
            name='language_from',
        ),
        migrations.RemoveField(
            model_name='languageexposure',
            name='language_hours_per_day',
        ),
        migrations.AlterField(
            model_name='languageexposure',
            name='age_of_acquisition',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(72)]),
        ),
    ]
