# Generated by Django 3.1.13 on 2022-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_auto_20211126_0157"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="race",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
