# Generated by Django 3.1.14 on 2022-09-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_child_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="source",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="dataset_name",
            field=models.CharField(max_length=121),
        ),
    ]
