# encoding: utf8
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='English_WG',
            fields=[
                ('basetable_ptr', models.OneToOneField(auto_created=True, primary_key=True, to_field='id', serialize=False, to='instruments.BaseTable')),
                ('item_respname', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_respno', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_reactmd', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_arehngry', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_aretired', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_becarefl', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_bequiet', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_claphand', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_cgdiaper', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_comehere', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_mdhome', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_wantmore', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_dontdo', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_dontouch', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_getup', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_givemom', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_givehug', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_givekiss', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_goget', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_goodgb', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_holdstil', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_gobyebye', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_lookhere', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_openmth', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_sitdown', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_spitout', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_stopit', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_gonight', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_throwbll', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_litpiggy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_wantride', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_imitate', models.CharField(max_length=20, null=True, choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_label', models.CharField(max_length=20, null=True, choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_baa_baa', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_choo_choo', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cockadoodledoo', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_grrr', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_meow', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_moo', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_ouch', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_quack_quack', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_uh_oh', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_vroom', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_woof_woof', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_yum_yum', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_animal', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bear', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bee', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bird', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bug', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bunny', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_butterfly', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cat', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_chicken_animal', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cow', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_deer', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dog', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_donkey', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_duck', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_elephant', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_fish_animal', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_frog', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_giraffe', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_goose', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_horse', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_kitty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_lamb', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_lion', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_monkey', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_mouse', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_owl', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_penguin', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pig', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pony', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_puppy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sheep', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_squirrel', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_teddybear', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tiger', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_turkey', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_turtle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_airplane', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bicycle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bus', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_car', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_firetruck', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_motorcycle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_stroller', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_train', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_truck', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_ball', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_balloon', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_block', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_book', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bubbles', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_doll', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pen', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_toy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_apple', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_banana', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bread', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_butter', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cake', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_candy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_carrots', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cereal', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cheerios', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cheese', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_chicken_food', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_coffee', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cookie', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cracker', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_drink_beverage', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_egg', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_fish_food', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_food', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_ice_cream', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_juice', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_meat', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_milk', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_noodles', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_orange', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_peas', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pizza', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_raisin', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_spaghetti', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_toast', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_water_beverage', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_beads', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bib', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_boots', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_button', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_coat', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_diaper', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dress', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hat', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_jacket', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_jeans', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_necklace', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pajamas', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pants', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_shirt', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_shoe', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_shorts', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sock', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sweater', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_zipper', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_arm', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_belly_button', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cheek', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_ear', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_eye', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_face', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_foot', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_finger', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hair', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hand', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_head', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_knee', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_leg', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_mouth', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_nose', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_owie', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tooth', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_toe', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tongue', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tummy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bathroom', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bathtub', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bed', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bedroom', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_chair', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_couch', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_crib', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_door', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_drawer', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_garage', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_high_chair', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_kitchen', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_living_room', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_oven', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_play_pen', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_potty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_refrigerator', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_rocking_chair', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sink', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_stairs', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_stove', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_table', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tv', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_window', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_blanket', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bottle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bowl', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_box', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_broom', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_brush', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_clock', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_comb', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cup', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dish', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_fork', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_glass', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_glasses', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hammer', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_keys', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_lamp', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_light', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_medicine', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_money', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_paper', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_penny', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_picture', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pillow', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_plant', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_plate', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_purse', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_radio', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_scissors', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_soap', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_spoon', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_telephone', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_toothbrush', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_towel', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_trash', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_vacuum', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_watch_object', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_backyard', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_beach', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_church', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_flower', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_garden', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_home', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_house', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_moon', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_outside', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_park', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_party', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pool', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_rain', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_rock', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_school', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_shovel', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sky', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_slide', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_snow', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_star', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_store', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sun', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_swing_object', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tree', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_water_not_beverage', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_work', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_zoo', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_aunt', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_baby', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_babysitter', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_babysitter_name', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_boy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_brother', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_child', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_daddy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_girl', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_grandma', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_grandpa', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_lady', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_man', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_mommy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_child_own_name', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_people', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_person', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sister', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_teacher', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_uncle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bath', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_breakfast', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bye', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dinner', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dont', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hello', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hi', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_lunch', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_nap', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_nightnight', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_no', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pattycake', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_peekaboo', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_please', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_shh', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_thank_you', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_wait', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_wanna', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_yes', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bite', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_blow', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_break', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bring', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bump', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_clean_action', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_close', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cry', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dance', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_draw', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_drink_action', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_drive', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_eat', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_fall', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_feed', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_finish', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_get', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_give', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_go', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_help', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hit', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hug', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hurry', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_jump', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_kick', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_kiss', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_look', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_love', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_open', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_play', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pull', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_push', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_put', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_read', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_ride', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_run', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_say', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_see', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_show', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sing', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sleep', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_smile', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_splash', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_stop', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_swim', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_swing_action', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_take', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_throw', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tickle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_touch', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_watch_action', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_walk', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_wash', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_wipe', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_write', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_day', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_later', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_morning', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_night', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_now', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_today', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tomorrow', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tonight', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_allgone', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_asleep', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_bad', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_big', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_blue', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_broken', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_careful', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_clean_description', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cold', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_cute', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dark', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dirty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_dry', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_empty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_fast', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_fine', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_gentle', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_good', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_happy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hard', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hot', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hungry', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_hurt', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_little', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_naughty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_nice', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_old', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_pretty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_red', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_scared', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sick', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_sleepy', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_soft', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_thirsty', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_tired', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_wet', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_yucky', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_his', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_her', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_it', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_me', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_mine', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_my', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_that', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_this', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_you', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_your', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_how', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_what', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_when', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_where', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_who', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_why', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_away', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_back', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_down', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_in', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_inside', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_off', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_on', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_out', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_there', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_under', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_up', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_all', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_another', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_more', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_none', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_not', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_other', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_same', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_some', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_armshow', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_reachout', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_points', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_waves', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_pickup', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_shakhead', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_nodhead', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_showhush', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_request', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_blowkiss', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_smacklip', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_shrugs', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_playpeek', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_patycak2', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_sobig', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_chase', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_dosing', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_dodance', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_eatspoon', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_drinkcup', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_combhair', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_bshteeth', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_wipeface', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_puthat', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_putshoe', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_putwatch', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_ptdsleep', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_blowhot', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_flyplane', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_ptndtele', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_snifflow', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_pushcar', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_throwges', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_ptndpour', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_ptndstir', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_putobed', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_cover', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_feedbotl', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_feedspon', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_brushit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_burbit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_pushit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_rockit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_kissit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_dressit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_wipeit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_talkit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_diaperit', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_sweep', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_putkey', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_pound', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_usesaw', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_type', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_ptndread', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_dovacuum', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_waterplt', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_playmus', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_ptnddriv', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_washdish', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_usecloth', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_usepen', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_dig', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_wearglas', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
            ],
            options={
            },
            bases=('instruments.basetable',),
        ),
    ]
