# Generated by Django 3.1.7 on 2022-03-29 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0004_auto_20220325_0459"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_640",
        ),
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_641",
        ),
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_642",
        ),
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_643",
        ),
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_644",
        ),
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_645",
        ),
        migrations.RemoveField(
            model_name="hebrew_ws",
            name="item_646",
        ),
    ]
