# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0005_auto_20140504_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wg',
            name='basetable_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='instruments.BaseTable'),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_airplne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_allgone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_animal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_another',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_apple',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_arm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_armshow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_asleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_aunt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_baabaa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_baby',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_babystr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_back',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_backyrd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_balloon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_banana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bath',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bathrm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bathtub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_beach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_beads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bedroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bib',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bicycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_big',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bird',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_blanket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bllybtn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_block',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_blow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_blowhot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_blowkiss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_book',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_boots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bottle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bowl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_boy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_break',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bring',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_brkfast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_broken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_broom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_brother',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_brush',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_brushit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bshteeth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bubbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bunny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_burbit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_butrfly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_butter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_button',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_bye',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_candy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_careful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_carrots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cckddld',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cereal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_chair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_chase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_chcken1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_chcken2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cheek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cheese',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cherios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_choocho',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_church',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_clean1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_clean2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_clock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_close',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_coat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_coffee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_comb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_combhair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cookie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_couch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cover',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cracker',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_crib',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_cute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_daddy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_deer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_diaper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_diaperit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dirty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dodance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dog',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_doll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_donkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dont',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_door',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dosing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dovacuum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_drawer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dressit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_drink1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_drink2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_drinkcup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_drive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_dry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_duck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_eat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_eatspoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_elephnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_empty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_eye',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_face',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_fall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_fast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_feed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_feedbotl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_feedspon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_finger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_firetrk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_fish1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_fish2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_flower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_flyplane',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_foot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_fork',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_frog',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_garden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_gentle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_gesta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_gestb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_gestc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_gestd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_geste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_get',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_giraffe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_girl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_give',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_glass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_glasses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_go',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_goose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_grandma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_grandpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_grr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hammer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_headp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_headu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hello',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_help',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_her',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_highchr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_his',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_horse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_house',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_how',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hungry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hurry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_hurt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_icecrem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_it',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_jacket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_jeans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_juice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_jump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_keys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_kick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_kiss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_kissit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_kitty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_knee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_lady',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_lamb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_lamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_later',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_leg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_light',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_lion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_little',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_livngrm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_look',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_love',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_man',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_me',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_medicne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_meow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_milk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_mine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_mommy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_monkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_moo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_moon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_more',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_morning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_mouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_mouth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_mtrcycl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_my',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_nameslf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_namestr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_nap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_naughty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ncklace',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_nghtnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_nice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_night',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_nodhead',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_none',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_noodles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_nose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_not',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_open',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_orange',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ouch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_oven',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_owie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_owl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_padj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pajamas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_panimals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_park',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_party',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_patycak2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pbodypt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pcloth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_peas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_peekabo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_penguin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_penny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pfoods',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pfurn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pickup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_picture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pig',
            field=models.IntegerField(default=0),
        ),
]
