# encoding: utf8
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20141217_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norwegian_WG',
            fields=[
                ('basetable_ptr', models.OneToOneField(auto_created=True, primary_key=True, to_field='id', serialize=False, to='instruments.BaseTable')),
                ('item_i_1_1', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_i_1_2', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_i_1_3', models.CharField(max_length=20, null=True, choices=[('yes', 'yes'), ('no', 'no')])),
                ('item_i_2_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_24', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_25', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_2_26', models.CharField(max_length=20, null=True, choices=[('understands', 'understands')])),
                ('item_i_3_1', models.CharField(max_length=20, null=True, choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_3_2', models.CharField(max_length=20, null=True, choices=[('never', 'never'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_4_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_4_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_24', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_25', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_26', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_27', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_28', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_29', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_30', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_31', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_32', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_33', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_34', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_35', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_5_36', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_6_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_7_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_24', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_25', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_26', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_27', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_8_28', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_9_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_10_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_24', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_25', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_26', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_27', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_28', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_29', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_30', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_31', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_32', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_33', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_34', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_11_35', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_12_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_13_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_14_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_15_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_16_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_24', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_25', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_26', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_27', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_28', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_29', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_30', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_31', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_32', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_33', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_34', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_35', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_36', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_37', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_38', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_39', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_40', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_41', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_42', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_43', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_44', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_45', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_46', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_47', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_48', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_49', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_50', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_51', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_52', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_17_53', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_17', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_18', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_19', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_20', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_21', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_22', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_23', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_24', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_25', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_26', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_27', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_28', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_29', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_30', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_31', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_32', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_33', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_34', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_35', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_18_36', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_19_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_20_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_21_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_21_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_21_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_21_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_21_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_21_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_10', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_11', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_12', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_13', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_14', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_15', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_22_16', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_1', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_2', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_3', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_4', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_5', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_6', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_7', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_8', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_23_9', models.CharField(max_length=20, null=True, choices=[('understands', 'understands'), ('produces', 'produces')])),
                ('item_i_24_1', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_2', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_3', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_4', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_5', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_6', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_7', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_8', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_9', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_10', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_11', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_24_12', models.CharField(max_length=20, null=True, choices=[('not yet', 'not yet'), ('sometimes', 'sometimes'), ('often', 'often')])),
                ('item_i_25_1', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_25_2', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_25_3', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_25_4', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_25_5', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_25_6', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_1', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_2', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_3', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_4', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_5', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_6', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_7', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_8', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_9', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_10', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_11', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_12', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_13', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_14', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_15', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_16', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_26_17', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_1', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_2', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_3', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_4', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_5', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_6', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_7', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_8', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_9', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_10', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_11', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_12', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_27_13', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_1', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_2', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_3', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_4', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_5', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_6', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_7', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_8', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_9', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_10', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_11', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_12', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_13', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_14', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
                ('item_i_28_15', models.CharField(max_length=20, null=True, choices=[('no', 'no'), ('yes', 'yes')])),
            ],
            options={
            },
            bases=('instruments.basetable',),
        ),
    ]
