# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_auto_20140926_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wg',
            name='col_pillow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pizza',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_plant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_plate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_playmus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_playpeek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_playpen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_please',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pony',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_potty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pound',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ppeoples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pplaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ppreploc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ppro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pquant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pques',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pretty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_prout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_psmhouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_psounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptdsleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptimewd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptnddriv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptndpour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptndread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptndstir',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptndtele',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ptoys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pttycak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pull',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_puppy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_purse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_push',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pushcar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pushit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_put',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_puthat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_putkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_putobed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_putshoe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_putwatch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pvehic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_pverbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_quckqck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_radio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_rain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_raisin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_rcknchr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_reachout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_request',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_rfrgrtr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ride',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_rock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_rockit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_same',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_say',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_scared',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_school',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_scisors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_see',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shakhead',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sheep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shirt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shoe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shorts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shovel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_show',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_showhush',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_shrugs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sink',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sister',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sleepy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_slide',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_smacklip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_smile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_snifflow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_snow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_soap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sobig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_soft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_some',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_spghett',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_splash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_spoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_squirrl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_stairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_stop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_store',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_stove',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_stroler',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sweater',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_sweep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_swim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_swing1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_swing2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_table',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_take',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_talkit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_teacher',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tedyber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_telphon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_that',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_there',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_thirsty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_this',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_thnkyou',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_throw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_throwges',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tickle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tiger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_toast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_toe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tomrrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tongue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tonight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tooth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_touch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_towel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_toy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_train',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_trash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_truck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tthbrsh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tummy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_turkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_turtle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_tv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uadj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uanimals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ubodypt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ucloth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ufoods',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_ufurn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uhoh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uncle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_under',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_upeoples',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uplaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_upreploc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_upro',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uquant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uques',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_urout',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_usecloth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_usepen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_usesaw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_usmhouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_usounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_utimewd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_utoys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uvehic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_uverbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_vacuum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_vroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wait',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_walk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wanna',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_washdish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_watch1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_watch2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_water1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_water2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_waterplt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_waves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wearglas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_what',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_when',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_where',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_who',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_why',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_window',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wipe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wipeface',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_wipeit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_woofwof',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_write',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_you',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_your',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_yucky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_yumyum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_zipper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wg',
            name='col_zoo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='basetable_ptr',
            field=models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='instruments.BaseTable'),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_about',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_above',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_after',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_airplane',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_allgone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_alligatr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_alot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_am',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_an',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_animal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ankle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_another',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_any',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_apple',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_applesac',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_are',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_arm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_around',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_asleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_aunt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_awake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_baabaa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_baby',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_babysttr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_back',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_backyard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_balloon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_banana',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_basement',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_basket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bath',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bathtub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_be',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_beach',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_beads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_beans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_because',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bedroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_behind',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_belt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bench',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_beside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_better',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bib',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bicycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_big',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bird',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_black',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blanket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blew',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bllybttn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_block',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blockses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_boat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_book',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_boots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bottle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bowl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_box',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_boy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bread',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_break',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_breaked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_breakfst',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bring',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bringed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_broke',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_broked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_broken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_broom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_brother',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_brown',
            field=models.IntegerField(default=0),
        ),
]
