# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20140926_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ws',
            name='col_brush',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bubbles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bucket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_build',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bunny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_but',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_butter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_buttocks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_button',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_buttrfly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_buy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_buyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_bye',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_callnphn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_came',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_camed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_camera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_camping',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_can1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_can2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_candy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_car',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_careful',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_carrots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_carry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_catch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cereal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chalk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chase',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cheek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cheerios',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cheese',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chicken1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chicken2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_child',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_childrns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_childs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_chocolat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_choochoo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_church',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_circus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_clap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_clean1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_clean2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_climb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_clock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_close',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_closet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cloud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_clown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_coat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cockddld',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_coffee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_coke',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_comb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_comed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx01',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx02',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx03',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx04',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx05',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx06',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx07',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx08',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx09',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx11',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx13',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx14',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx16',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx17',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx18',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx19',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx20',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx21',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx22',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx23',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx24',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx25',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx26',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx27',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx28',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx29',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx30',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx31',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx32',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx33',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx34',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx35',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx36',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_complx37',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_connand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_connif',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_connso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_connthen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cook',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cookie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_corn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_couch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_could',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_country',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cover',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cowboy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cracker',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_crayon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_crib',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_cute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_daddy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_deer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_diaper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_did',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dirty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_do',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_doctor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_doed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_does',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dog',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_doll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_donkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dont',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_donut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_door',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_downtown',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dranked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drawer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drink1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drink2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drinked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_drove',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dry1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dry2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dryer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_duck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_dump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_each',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_eat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_eated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_egg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_elephant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_empty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_every',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_eye',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_face',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_falled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_farm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_feed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_feet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_feets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fell',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_find',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_finger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fireman',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_firetrck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_first',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fish1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fish2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fix',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_flew',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_flied',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_flower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_foot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_foots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_fork',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_friend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_frnchfrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_frog',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_full',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_garage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_garbage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_garden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gasstatn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gentle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_get',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_getted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_giraffe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_girl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_give',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_givemefv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_glass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_glasses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gloves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_glue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_go',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_goed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gonna',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gonnagty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_goose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gopotty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_got',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gotta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gotted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_grandma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_grandpa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_grapes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_grass',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_green',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_greenbns',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_grr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_gum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_had',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hafta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hair',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hamburgr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hammer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_have',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_haved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_he',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_head',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_heard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_heared',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_heavy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_held',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_helicptr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hello',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_help',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_her',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_here',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hide',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_highchar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_him',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_his',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_holded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_horse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_house',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_how',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hungry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hurry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_hurt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_i',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_icecream',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_inside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_into',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_is',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_it',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_jacket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_jar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_jeans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_jello',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_jelly',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_juice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_jump',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_keys',
            field=models.IntegerField(default=0),
        ),
    ]
