# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_auto_20140926_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ws',
            name='col_kick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_kiss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_kitchen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_kitty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_knee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_knife',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_knock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ladder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lady',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lamb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lamp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_last',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_later',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lawnmowr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_leg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lemme',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_light',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lips',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_listen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_little',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_livingrm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lollipop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_long',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_look',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_losed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_losted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_loud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_love',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mailman',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_make',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_maked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_man',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mans',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_me',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_medicine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_melon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_men',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_meow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_milk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mine',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mittens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mommy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_monkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_moo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_moon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_moose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_more',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_morning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_motrcycl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mouse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mouses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_mouth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_movie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_much',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_muffin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_my',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_myself',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nail',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_namepet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nameself',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_namesttr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_napkin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_naughty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_necklace',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_need',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_new',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nextto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nghtnght',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_night',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_noisy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_none',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_noodles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_now',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nurse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_nuts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_of',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_off',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_old',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ontopof',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_open',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_orange1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_orange2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ouch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_our',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_outside',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_oven',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_over',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_owie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_owl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_paint',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pajamas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pancake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_paper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_park',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_party',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_patycak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_peas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_peekaboo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pencil',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_penguin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_penis',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_penny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pentbttr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pickle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_picnic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_picture',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pillow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pizza',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_plant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_plate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_play',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_playdogh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_playgrnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_playpen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_please',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_police',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pony',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_poor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_popcorn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_popsicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_porch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_potatchp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_potato',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_potty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_prepat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_prepby',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_prepto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_prepup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_prepwith',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pretend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pretty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pretzel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pudding',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pull',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_pumpkin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_punder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_puppy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_purse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_push',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_put',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_puzzle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_quackqck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_quantall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_quantnot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_quiet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_radio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_rain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_raisin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ran',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ranned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_rckngchr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_red',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_refrgrtr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_ride',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_rip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_rock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_roof',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_rooster',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_runned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_salt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_same',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sandbox',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sandwich',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_satted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sauce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_saw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_say',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_scared',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_scarf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_school',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_scissors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_see',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_seed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_share',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_she',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sheep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shirt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shoe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shoeses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shopping',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shorts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shoulder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shovel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_show',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_shower',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sidewalk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sink',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sister',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_skate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sleep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sleepy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_slide1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_slide2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_slipper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_slow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_smile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_snack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sneaker',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_snow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_snowman',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_snowsuit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_soap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sobig',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sockses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_soda',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sofa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_soft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_some',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_soup',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_spaghett',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_spill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_splash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_splural',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_spoon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_spossess',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sprinklr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_squirrel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stick',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sticky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stop',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_store',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_story',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stove',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_street',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stroller',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_strwbrry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_stuck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sun',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sweater',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_sweep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_swim',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_swing1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_swing2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_table',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_take',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_taked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_talk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tape',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_taste',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_teacher',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_teddyber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_teeth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_teeths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_telephon',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_thankyou',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_that',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_the',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_their',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_them',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_there',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_these',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_they',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_think',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_thirsty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_this',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_those',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_throw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_thslttlp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tickle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tiger',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tights',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tiny',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tired',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tissue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_toast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_toe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_toeses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tomorrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tongue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tonight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_too',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_took',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tooth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tooths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tothbrsh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_touch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_towel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_toy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tractor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_train',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_trash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tray',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tricycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_truck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_try',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tummy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tuna',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_turkey',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_turnarnd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_turtle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_tv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_uhoh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_uncle',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_undrpnts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_us',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_usecmpl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_usefut',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_usemiss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_usepast',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_useposs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_vacuum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_vagina',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_vanilla',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_vitamins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_vroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wait',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wake',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_walk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_walker',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wanna',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_was',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_watch1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_watch2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_water1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_water2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_we',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_went',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wented',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_were',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_what',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_when',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_where',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_which',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_white',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_who',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_why',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_will',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wind',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_window',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_windy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wipe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wolf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_woods',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_woofwoof',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_work1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_work2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_would',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_write',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_wshngmch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yellow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yesterdy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yogurt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_you',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_your',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yourself',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yucky',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_yumyum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_zebra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_zipper',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ws',
            name='col_zoo',
            field=models.IntegerField(default=0),
        ),
    ]
