# Generated by Django 3.1.13 on 2022-04-08 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0017_spanish_argentinian_ws"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="American_Sign_Language_CDI",
            new_name="American_Sign_Language_CDITwo",
        ),
    ]
