# Generated by Django 3.1.13 on 2022-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0020_auto_20220411_0154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_681",
            field=models.CharField(
                choices=[
                    ("not yet", "not yet"),
                    ("sometimes/often", "sometimes/often"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_682",
            field=models.CharField(
                choices=[
                    ("not yet", "not yet"),
                    ("sometimes/often", "sometimes/often"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_683",
            field=models.CharField(
                choices=[
                    ("not yet", "not yet"),
                    ("sometimes/often", "sometimes/often"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_684",
            field=models.CharField(
                choices=[
                    ("not yet", "not yet"),
                    ("sometimes/often", "sometimes/often"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_685",
            field=models.CharField(
                choices=[
                    ("not yet", "not yet"),
                    ("sometimes/often", "sometimes/often"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_711",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_712",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_713",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_714",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_715",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_716",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_717",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_718",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_719",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_720",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_721",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_722",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_723",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_724",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_725",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_726",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_727",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_728",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_729",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_730",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_731",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_732",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_733",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_734",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_735",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_736",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_737",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_738",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_739",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_740",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_741",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_742",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_743",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_744",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_745",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_746",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spanish_mexican_ws",
            name="item_747",
            field=models.CharField(
                choices=[("simple", "simple"), ("complex", "complex")],
                max_length=8,
                null=True,
            ),
        ),
    ]
