# Generated by Django 3.1.13 on 2022-05-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0032_persian_wg_persian_ws"),
    ]

    operations = [
        migrations.AddField(
            model_name="persian_wg",
            name="item_401",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_402",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_403",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_404",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_405",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_406",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_407",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_408",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_409",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_410",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_411",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_412",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_413",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_414",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_415",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_416",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_417",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_418",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_419",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_420",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_421",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_422",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_423",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_424",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_425",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_426",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_427",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_428",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_429",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_430",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_431",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_432",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="persian_wg",
            name="item_433",
            field=models.CharField(max_length=11, null=True),
        ),
    ]
