# Generated by Django 3.1.13 on 2022-07-22 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0037_auto_20220715_0256"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="henry_test_language_wg",
            name="basetable_ptr",
        ),
        migrations.DeleteModel(
            name="Henry_Second_Language_WG",
        ),
        migrations.DeleteModel(
            name="Henry_Test_Language_WG",
        ),
    ]
