# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 23:42
from __future__ import unicode_literals

from django.db import migrations

def rename_sources(apps, schema_editor):
    Source = apps.get_model("common", "Source")
    Instrument = apps.get_model("common", "Instrument")

    Source.objects.filter(instrument_language = 'Mandarin').update(instrument_language = 'Mandarin (Beijing)')
    Instrument.objects.filter(language = 'Mandarin').update(language = 'Mandarin (Beijing)')


def undo_rename_sources(apps, schema_editor):
    Source = apps.get_model("common", "Source")
    Instrument = apps.get_model("common", "Instrument")
    
    Source.objects.filter(instrument_language = 'Mandarin (Beijing)').update(instrument_language = 'Mandarin')
    Instrument.objects.filter(language = 'Mandarin (Beijing)').update(language = 'Mandarin')


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0039_mandarin_taiwanese_wg_mandarin_taiwanese_ws'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mandarin_IC',
            new_name='Mandarin_Beijing_IC',
        ),
        migrations.RenameModel(
            old_name='Mandarin_TC',
            new_name='Mandarin_Beijing_TC',
        ),
        migrations.RenameModel(
            old_name='Mandarin_WS',
            new_name='Mandarin_Beijing_WS',
        ),
        migrations.RunPython(rename_sources, undo_rename_sources),
    ]
