# Generated by Django 3.1.14 on 2023-11-28 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0039_auto_20231127_0440"),
    ]

    operations = [
        migrations.AddField(
            model_name="french_french_ws",
            name="item_717",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
