# Generated by Django 3.1.14 on 2023-12-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0047_auto_20231214_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='english_american_wg',
            name='item_445',
            field=models.CharField(max_length=1, null=True),
        ),
        
    ]
