# Generated by Django 3.1.14 on 2023-12-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0050_auto_20231214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='english_american_wg',
            name='item_466',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='english_american_wg',
            name='item_478',
            field=models.CharField(max_length=11, null=True),
        ),
        
    ]
