# Generated by Django 3.1.14 on 2023-12-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0052_auto_20231218_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='french_french_wg',
            name='item_796',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='french_french_wg',
            name='item_797',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='french_french_wg',
            name='item_798',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='french_french_wg',
            name='item_799',
            field=models.CharField(max_length=11, null=True),
        ),
        
    ]
