```{r}
setwd("~/Documents/repo/wordbank/incoming_data/Korean_Yim/")

library(tidyverse)
library(lubridate)
library(magrittr)
```

```{r}
korean_wg <- readxl::read_excel("Project Form_KMBCDI(infant)_Sample & Batch 2-3_16 40 Records (Consolidated Files)_Updated.xlsx",skip = 2)
korean_ws <- readxl::read_excel("Project Form_KMBCDI(toddler)_Sample & Batch 3-16 156 Records (Consolidated Files) 2.xlsx",skip = 2)

korean_words <- read_csv("Korean_subsections.csv")

subsections <- readxl::read_excel("K-CDI_data_EWHA.xlsx")

instrument_wg <- read_csv("[Korean_WG].csv")
uni_lemmas_wg <- read_csv("unilemma_korean_wg.csv") %>% filter(!is.na(itemID))
instrument_ws <- read_csv("[Korean_WS].csv")
uni_lemmas_ws <- read_csv("unilemma_korean_ws.csv") %>% filter(!is.na(itemID))
multi_lemmas_wg <- readxl::read_excel("multiple_lemmas_wg_EWHA.csv.xlsx")
multi_lemmas_ws <- readxl::read_excel("multiple_lemmas_ws_EWHA.csv.xlsx")

```

```{r}
names(korean_wg)[1:6] <- c("s_no",	"subj_num",	"dot",	"dob",	"gender",	"age")
names(korean_ws)[1:6] <- c("s_no",	"subj_num",	"dot",	"dob",	"gender",	"age")

korean_wg$age_months <- korean_ws$age_months <- NA

korean_wg <- korean_wg[,c(1:6,ncol(korean_wg),7:(ncol(korean_wg)-1))]
korean_ws <- korean_ws[,c(1:6,ncol(korean_ws),7:(ncol(korean_ws)-1))]


names(korean_wg)[8:ncol(korean_wg)] <- sprintf("item_%03d", seq(1,(ncol(korean_wg)-7)))
names(korean_ws)[8:ncol(korean_ws)] <- sprintf("item_%03d", seq(1,(ncol(korean_ws)-7)))

korean_wg$dot <- format(parse_date_time(korean_wg$dot, "Ymd", truncated = 3),"%m/%d/%Y")
korean_ws$dot <- format(parse_date_time(korean_ws$dot, "Ymd", truncated = 3),"%m/%d/%Y")
korean_wg$dob <- format(parse_date_time(korean_wg$dob, "Ymd", truncated = 3),"%m/%d/%Y")
korean_ws$dob <- format(parse_date_time(korean_ws$dob, "Ymd", truncated = 3),"%m/%d/%Y")

wg_ages <- as.duration(interval(parse_date(korean_wg$dob,format = "%m/%d/%Y"), parse_date(korean_wg$dot,format = "%m/%d/%Y")))
ws_ages <- as.duration(interval(parse_date(korean_ws$dob,format = "%m/%d/%Y"), parse_date(korean_ws$dot,format = "%m/%d/%Y")))

korean_wg$age_months <- round(time_length(wg_ages, "days")/(365.2425/12.0))
korean_ws$age_months <- round(time_length(ws_ages, "days")/(365.2425/12.0))

korean_wg$dob <- korean_ws$dob <- NULL

```

```{r}

uni_lemmas_wg %<>%
  rename(uni_lemma = uni_list) %>%
  left_join(multi_lemmas_wg %>% select(uni_lemma, itemID, include),
            by = c("itemID","uni_lemma")) %>%
  filter(include == 1 | is.na(include)) %>%
  select(-starts_with('X'))

uni_lemmas_ws %<>%
  rename(uni_lemma = uni_list) %>%
  left_join(multi_lemmas_ws %>% select(uni_lemma, itemID, include),
            by = c("itemID","uni_lemma")) %>%
  filter(include == 1 | is.na(include)) %>%
  select(-starts_with('X'))

instrument_wg %<>% 
  left_join(uni_lemmas_wg %>% select(uni_lemma, itemID)) %>%
  mutate(uni_lemma = ifelse(type == 'word', uni_lemma, NA))

instrument_ws %<>% 
  left_join(uni_lemmas_ws %>% select(uni_lemma, itemID)) %>%
  mutate(uni_lemma = ifelse(type == 'word', uni_lemma, NA))

instrument_wg$item <- sprintf("item_%03d", seq(1,nrow(instrument_wg)))
instrument_ws$item <- sprintf("item_%03d",seq(1,nrow(instrument_ws)))

View(inner_join(instrument_wg,instrument_ws, by=c("definition","category")) %>%
       filter(uni_lemma.x != uni_lemma.y) %>%
       select(itemID.x,itemID.y,definition, gloss.x,gloss.y, uni_lemma.x, uni_lemma.y))
```

```{r}
# summed_wg <- korean_wg %>%
#   gather(key = item_id, value = score, item_001:item_284) %>%
#   left_join(filter(korean_words, form == 'infant')[,c("item_id","section")]) %>%
#   group_by(subj_num, section) %>%
#   summarise(comp = sum(score %in% c("U","P"), na.rm = T),
#             prod = sum(score == "P", na.rm = T)) %>%
#   group_by(subj_num) %>%
#   summarise(total_prod = sum(prod), total_comp = sum(comp))
# 
# summed_ws <- korean_ws %>%
#   gather(key = item_id, value = score, item_001:item_641) %>%
#   left_join(filter(korean_words, form == 'toddler')[,c("item_id","section")]) %>%
#   group_by(subj_num, section) %>%
#   summarise(comp = sum(score %in% c("U","P"), na.rm = T),
#             prod = sum(score == "P", na.rm = T)) %>%
#   group_by(subj_num) %>%
#   summarise(total_prod = sum(prod), total_comp = sum(comp))
```

```{r}
korean_wg$gender[korean_wg$subj_num == "IN1017"] <- "F"
korean_wg$gender[korean_wg$subj_num == "IN1018"] <- "M"
korean_wg$gender[korean_wg$subj_num == "IN1019"] <- "M"
korean_wg$gender[korean_wg$subj_num == "IN1024"] <- "M"
korean_wg$gender[korean_wg$subj_num == "IN2004"] <- "M"

korean_ws$dot[korean_ws$subj_num == "TO3078"] <- "12/03/2016"
korean_ws$dot[korean_ws$subj_num == "TO4003"] <- "12/13/2016"


```


```{r}
write_csv(korean_wg, "../../raw_data/Korean_WG/KoreanWG_Yim_data.csv", na = "")
write_csv(korean_ws, "../../raw_data/Korean_WS/KoreanWS_Yim_data.csv", na = "")

write_csv(instrument_wg, "../../raw_data/Korean_WG/[Korean_WG].csv", na = "")
write_csv(instrument_ws, "../../raw_data/Korean_WS/[Korean_WS].csv", na = "")

```

  