from django.contrib import admin

# Register your models here.

from instruments import models

class InstrumentAdmin (admin.ModelAdmin):
    search_fields = ['basetable_ptr_id']

for m in [
    models.British_Sign_Language_WG,
    models.Cantonese_WS,
    models.Croatian_WG,
    models.Croatian_WS,
    models.Danish_WG,
    models.Danish_WS,
    models.English_American_WG,
    models.English_American_WS,
    models.French_Quebecois_WG,
    models.French_Quebecois_WS,
    models.German_WS,
    models.Hebrew_WG,
    models.Hebrew_WS,
    models.Hungarian_WS,
    models.Italian_WG,
    models.Italian_WS,
    models.Mandarin_Beijing_IC,
    models.Mandarin_Beijing_TC,
    models.Mandarin_Beijing_WS,
    models.Norwegian_WG,
    models.Norwegian_WS,
    models.Russian_WG,
    models.Russian_WS,
    models.Slovak_WG,
    models.Slovak_WS,
    models.Spanish_Mexican_WG,
    models.Spanish_Mexican_WS,
    models.Swedish_WG,
    models.Swedish_WS,
    models.Turkish_WG,
    models.Turkish_WS,
    models.English_British_TEDS_Twos,
    models.English_British_TEDS_Threes,
    models.American_Sign_Language_FormA,
    models.American_Sign_Language_FormBOne,
    models.American_Sign_Language_FormBTwo,
    models.American_Sign_Language_FormC,
    models.Greek_Cypriot_WS,
    models.Kigiriama_WG,
    models.Kigiriama_WS,
    models.Kiswahili_WG,
    models.Kiswahili_WS,
    models.Czech_WS,
    models.English_Australian_WS,
    models.English_British_Oxford_CDI,
    models.Latvian_WG,
    models.Latvian_WS,
    models.Korean_WG,
    models.Korean_WS,
    models.French_French_WG,
    models.French_French_WS,
    models.Spanish_European_WG,
    models.Spanish_European_WS,
    models.Portuguese_European_WG,
    models.Portuguese_European_WS,
    models.Mandarin_Taiwanese_WG,
    models.Mandarin_Taiwanese_WS,
    models.English_Irish_WS,
    models.Irish_WS,
    models.Finnish_WS,
    models.American_Sign_Language_CDITwo,
    models.Dutch_Swingley,
    models.Dutch_WS,
    models.Dutch_WG,
    models.Dutch_FormOne,
    models.Dutch_FormTwoA,
    models.Dutch_FormTwoB,
    models.Dutch_FormThree,
    models.Spanish_Argentinian_WS,
    models.Spanish_Chilean_WG,
    models.Spanish_Peruvian_WG,
    models.Spanish_Peruvian_WS,
    models.Persian_WS,
    models.Persian_WG,
    models.Finnish_WSShort,
    models.English_American_WSShort,
    models.English_American_WGShort,
    models.English_British_OxfordShort,
]:
    admin.site.register(m, InstrumentAdmin)
