from .schemas.British_Sign_Language_WG import *
from .schemas.Cantonese_WS import *
from .schemas.Croatian_WG import *
from .schemas.Croatian_WS import *
from .schemas.Danish_WG import *
from .schemas.Danish_WS import *
from .schemas.English_American_WG import *
from .schemas.English_American_WS import *
from .schemas.French_Quebecois_WG import *
from .schemas.French_Quebecois_WS import *
from .schemas.German_WS import *
from .schemas.Hebrew_WG import *
from .schemas.Hebrew_WS import *
from .schemas.Hungarian_WS import *
from .schemas.Italian_WG import *
from .schemas.Italian_WS import *
from .schemas.Mandarin_Beijing_IC import *
from .schemas.Mandarin_Beijing_TC import *
from .schemas.Mandarin_Beijing_WS import *
from .schemas.Norwegian_WG import *
from .schemas.Norwegian_WS import *
from .schemas.Russian_WG import *
from .schemas.Russian_WS import *
from .schemas.Slovak_WG import *
from .schemas.Slovak_WS import *
from .schemas.Spanish_Mexican_WG import *
from .schemas.Spanish_Mexican_WS import *
from .schemas.Swedish_WG import *
from .schemas.Swedish_WS import *
from .schemas.Turkish_WG import *
from .schemas.Turkish_WS import *
from .schemas.English_British_TEDS_Twos import *
from .schemas.English_British_TEDS_Threes import *
from .schemas.American_Sign_Language_FormA import *
from .schemas.American_Sign_Language_FormBOne import *
from .schemas.American_Sign_Language_FormBTwo import *
from .schemas.American_Sign_Language_FormC import *
from .schemas.Greek_Cypriot_WS import *
from .schemas.Kigiriama_WG import *
from .schemas.Kigiriama_WS import *
from .schemas.Kiswahili_WG import *
from .schemas.Kiswahili_WS import *
from .schemas.Czech_WS import *
from .schemas.English_Australian_WS import *
from .schemas.English_British_Oxford_CDI import *
from .schemas.Latvian_WG import *
from .schemas.Latvian_WS import *
from .schemas.Korean_WG import *
from .schemas.Korean_WS import *
from .schemas.French_French_WG import *
from .schemas.French_French_WS import *
from .schemas.Spanish_European_WG import *
from .schemas.Spanish_European_WS import *
from .schemas.Portuguese_European_WG import *
from .schemas.Portuguese_European_WS import *
from .schemas.Mandarin_Taiwanese_WG import *
from .schemas.Mandarin_Taiwanese_WS import *
from .schemas.English_Irish_WS import *
from .schemas.Irish_WS import *
from .schemas.Finnish_WS import *
from .schemas.American_Sign_Language_CDITwo import *
from .schemas.Dutch_Swingley import *
from .schemas.Dutch_WS import *
from .schemas.Dutch_WG import *
from .schemas.Dutch_FormOne import *
from .schemas.Dutch_FormTwoA import *
from .schemas.Dutch_FormTwoB import *
from .schemas.Dutch_FormThree import *
from .schemas.Spanish_Argentinian_WS import *
from .schemas.Spanish_Chilean_WG import *
from .schemas.Spanish_Peruvian_WG import *
from .schemas.Spanish_Peruvian_WS import *
from .schemas.Persian_WS import *
from .schemas.Persian_WG import *
from .schemas.Finnish_WSShort import *
from .schemas.English_American_WSShort import *
from .schemas.English_American_WGShort import *
from .schemas.English_British_OxfordShort import *
from .schemas.Arabic_Saudi_WG import *
from .schemas.Estonian_WS import *
from .schemas.Catalan_WS import *
from .schemas.Korean_WGComp import *
from .schemas.French_Quebecois_WG import *
from .schemas.Finnish_WGProdShort import *
from .schemas.Finnish_WGProd import *
from .schemas.English_American_WG import *
from .schemas.Finnish_WS import *
from .schemas.Arabic_Saudi_WS import *
from .schemas.Arabic_Saudi_WSOther import *
from .schemas.English_American_WG import *
