from schemas.Croatian_WG import *
from schemas.Croatian_WS import *
from schemas.Danish_WS import *
from schemas.English_WG import *
from schemas.English_WS import *
from schemas.German_WS import *
from schemas.Italian_WS import *
from schemas.Norwegian_WG import *
from schemas.Norwegian_WS import *
from schemas.Russian_WG import *
from schemas.Russian_WS import *
from schemas.Spanish_WG import *
from schemas.Spanish_WS import *
from schemas.Swedish_WG import *
from schemas.Swedish_WS import *
from schemas.Turkish_WG import *
from schemas.Turkish_WS import *
from schemas.Hebrew_WS import *
from schemas.Hebrew_WG import *
from schemas.Cantonese_WS import *
from schemas.Mandarin_WS import *
from schemas.British_Sign_Language_WG import *
from schemas.Mandarin_TC import *
from schemas.Italian_WG import *
from schemas.Danish_WG import *
from schemas.French_Quebec_WG import *
from schemas.Slovak_WG import *
from schemas.Slovak_WS import *
from schemas.French_Quebec_WS import *
from schemas.French_Quebec_WS import *
from schemas.English_British_TEDS_Twos import *
from schemas.English_British_TEDS_Threes import *
from schemas.American_Sign_Language_FormA import *
from schemas.American_Sign_Language_FormBOne import *
from schemas.American_Sign_Language_FormBTwo import *
from schemas.American_Sign_Language_FormC import *
from schemas.Cypriot_Greek_WS import *
from schemas.Kigiriama_WG import *
from schemas.Kigiriama_WS import *
from schemas.Kiswahili_WG import *
from schemas.Kiswahili_WS import *
from schemas.Mandarin_IC import *
from schemas.Czech_WS import *
from schemas.Australian_English_WS import *
from schemas.English_British_Oxford_CDI import *
from schemas.Latvian_WG import *
from schemas.Latvian_WS import *
from schemas.Korean_WG import *
from schemas.Korean_WS import *
