


```{r}
library(tidyverse)
library(lubridate)

setwd("~/Documents/repo/wordbank/incoming_data/Spanish_Redux/")

```

```{r}
spanishwg_instrument <- read_csv("../../raw_data/Spanish_WG/[Spanish_WG].csv")
spanishws_instrument <- read_csv("../../raw_data/Spanish_WS/[Spanish_WS].csv")

raw_spanishwg_fernald <- readxl::read_excel("SpanishWG_Fernald_Outreach.xlsx")
raw_spanishws_fernald <- readxl::read_excel("SpanishWS_Fernald_Outreach.xlsx")

raw_spanishwg_djm <- readxl::read_excel("SpanishWG_Marchman_Norming.xlsx", skip = 3)
raw_spanishws_djm <- read_csv("DJM_spantoditemsbysub_withdemo.csv")
```


```{r}
spanishwg_fernald <- raw_spanishwg_fernald %>%
  mutate(BOrder = as.numeric(as.character(BOrder)),
         MotherEd = as.numeric(as.character(MotherEd)),
         DOB = round(as.numeric(CDIDate - DOB)/(365.2425/12.0)),
         CDIDate = format(CDIDate, "%Y-%m-%d")) %>%
  rename(DataAge = DOB)

spanishwg_fernald_words <- unique(gsub("/U|/P","", names(spanishwg_fernald)[grepl("/U|/P", names(spanishwg_fernald))]))


spanishwg_fernald_fields <- data_frame(field = NA, 
                                       column = c(names(spanishwg_fernald)[1:9],
                                                  spanishwg_fernald_words,
                                                  names(spanishwg_fernald)[866:963]), 
                                       group = NA, type = NA)

spanishwg_fernald_fields %<>% 
  left_join(select(spanishwg_instrument, itemID, item, type) %>%
            mutate(item = toupper(item)),
         by = c('column' = 'item')) %>%
  mutate(field = itemID, type = type.y) %>%
  select(-itemID, -type.y, -type.x)

names(spanishwg_fernald) <- gsub("/","",names(spanishwg_fernald))
```


```{r}
spanishws_fernald <- raw_spanishws_fernald %>%
  mutate(BOrder = as.numeric(as.character(BOrder)),
         MotherEd = as.numeric(as.character(MotherEd)),
         DOB = round(as.numeric(CDIDate - DOB)/(365.2425/12.0)),
         CDIDate = format(CDIDate, "%Y-%m-%d")) %>%
  rename(DataAge = DOB)


spanishws_fernald_fields <- data_frame(field = NA, 
                                       column = names(spanishws_fernald), 
                                       group = NA, type = NA)

spanishws_fernald_fields %<>% 
  left_join(select(spanishws_instrument, itemID, item, type) %>%
            mutate(item = toupper(item)),
         by = c('column' = 'item')) %>%
  mutate(field = itemID, type = type.y) %>%
  select(-itemID, -type.y, -type.x)

```

```{r}
spanishwg_djm <- raw_spanishwg_djm %>%
  select(-months, -days) %>%
  mutate(DOB = round(as.numeric(CDIDate - DOB)/(365.2425/12.0)),
         CDIDate = format(CDIDate, "%Y-%m-%d")) %>%
  rename(DataAge = DOB)

names(spanishwg_djm)[439:536] <- tolower(names(spanishwg_djm)[439:536])

spanishwg_djm_fields <- data_frame(field = NA, 
                                       column = names(spanishwg_djm), 
                                       group = NA, type = NA)

spanishwg_djm_fields %<>% 
  left_join(select(spanishwg_instrument, itemID, item, type),
         by = c('column' = 'item')) %>%
  mutate(field = itemID, type = type.y) %>%
  select(-itemID, -type.y, -type.x)
```

```{r}
# Reserved for DJM WS
```

```{r}
write_csv(spanishwg_fernald, "SpanishWG_Fernald_Outreach_data.csv", na = "")
write_csv(spanishwg_fernald_fields, "SpanishWG_Fernald_Outreach_fields.csv", na = "")

write_csv(spanishws_fernald, "SpanishWS_Fernald_Outreach_data.csv", na = "")
write_csv(spanishws_fernald_fields, "SpanishWS_Fernald_Outreach_fields.csv", na = "")

write_csv(spanishwg_djm, "SpanishWG_Marchman_Norming_data.csv", na = "")
write_csv(spanishwg_djm_fields, "SpanishWG_Marchman_Norming_fields.csv", na = "")

```

