---
title: "Sex/Gender Differences in Vocabulary Development"
author: "Mika Braginsky and Dan Yurovsky"
date: "2015-04-22"
output:
  html_document:
    highlight: tango
    theme: spacelab
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE, message=FALSE, warning=FALSE)
font = "Open Sans"
```

```{r}
library(dplyr)
library(RMySQL)
library(tidyr)
library(ggplot2)
library(magrittr)
source('../../shiny_apps/data_loading.R')
```

Load in Wordbank common data.
```{r}
wordbank <- src_mysql(dbname='wordbank', host="54.149.39.46",
                      user="wordbank", password="wordbank")

common.tables <- get.common.tables(wordbank)

admins <- get.administration.data(common.tables$momed,
                                  common.tables$child,
                                  common.tables$instrumentsmap,
                                  common.tables$administration)

items <- get.item.data(common.tables$wordmapping,
                       common.tables$instrumentsmap,
                       common.tables$category)
```

Get by-child productive vocabulary data.
```{r}
num.words <- items %>%
  filter(form == "WS", type == "word") %>%
  group_by(language) %>%
  summarise(n = n())

vocab.admins <- admins %>%
  select(data_id, language, form, age, sex, production) %>%
  filter(form == "WS", !is.na(sex), sex != "")

vocab.data <- vocab.admins %>%
  group_by(language, sex, age) %>%
  left_join(num.words) %>%
  mutate(production = as.numeric(production)/n)

vocab.sample.sizes <- vocab.admins %>%
  group_by(language) %>%
  summarise(n = length(unique(data_id)))
vocab.data %<>% left_join(vocab.sample.sizes)
vocab.data %<>% mutate(label = sprintf("%s (n = %s)", language, n))
```

Fit models to vocabulary by age data and estimate the mean difference between female and male children for each language.
```{r}
dists <- vocab.data %>%
  group_by(language, sex) %>%
  do(pts = seq(min(.$age), max(.$age), 1),
     model = loess(production ~ age, data = .)) 
predictions <- do(dists, predictions = predict(.$model, data.frame(age=.$pts)))
predictions$language <- dists$language
predictions$sex <- dists$sex

areas <- predictions %>%
  spread(sex, predictions) %>%
  rename(Female = `F`,
         Male = M) %>%
  rowwise() %>%
  mutate(area = mean(Female - Male))
```

Plot mean difference by language.
```{r, fig.height=6, fig.width=9}
ggplot(areas, aes(x = language, y = area)) +
  geom_bar(stat = "identity", position = "dodge", fill = "steelblue") +
  theme_bw() +
  theme(text = element_text(family = font)) +
  xlab("Language") +
  ylab("Mean gender difference in vocabulary size across age")
```