---
title: "Crosstabs"
author: "Dan Yurovsky"
date: "September 30, 2014"
output: html_document
---

Load Required Libraries
```{r, echo=FALSE}
# clear all previous variables
rm(list=ls())

#get lab version of useful R functions
source('~/Projects/Other/Ranalysis/useful.R')

#load libraries for data manipulation and graphing
library(directlabels)
library(dplyr)
library(RSQLite)
library(RSQLite.extfuns)
library(RMySQL)
library(tidyr)
```

Load Database
```{r, echo=FALSE}
# connect to local databse
#wordbank <- src_sqlite('wordbank.sqlite')
wordbank <- src_mysql(dbname='wordbank')

#wordbank <- src_mysql(dbname='wordbank',host="54.200.250.120", 
#                      user="wordbank",password="wordbank")
# load all tables
admin.table <- tbl(wordbank,"common_administration")
child.table <- tbl(wordbank,"common_child")
instruments.table <- tbl(wordbank,"common_instrumentsmap")
source.table <- tbl(wordbank,"common_source")
wordinfo.table <- tbl(wordbank,"common_wordinfo")
mapping.table <- tbl(wordbank,"common_wordmapping")
ws.table <- tbl(wordbank,"instruments_ws")
wg.table <- tbl(wordbank,"instruments_wg")
cdi.cat.table <- tbl(wordbank,"common_cdicategory")
```

Load WS categories
```{r}
ws.categories <- merge(wordinfo.table,cdi.cat.table,
                       by.x="CDI_cat_id",by.y="id")[,2:3] %>%
  rename(category = name)
```

Load WG productive/receptive data
```{r}
wg.vocab.words <- as.data.frame(select(
  wg.table,basetable_ptr_id,col_baabaa:col_some))
names(wg.vocab.words)[1] <- "id"

wg.bykid.longform <- melt(wg.vocab.words,id.vars="id",
                       variable.name = "word",
                       value.name="produces") %>%
  mutate(understands = produces >= 1,
         produces = produces == 2)

wg.scores <- wg.bykid.longform %>%
  group_by(id) %>%
  summarise(productive = sum(produces),
            receptive = sum(understands))
```

Load WS productive data
```{r}
ws.vocab.words <- as.data.frame(select(
  ws.table,basetable_ptr_id,col_baabaa:col_connthen))
names(ws.vocab.words)[1] <- "id"
names(ws.vocab.words)[2:ncol(ws.vocab.words)] <- 
  lapply(names(ws.vocab.words)[2:ncol(ws.vocab.words)],
         function(x) substr(x,5,nchar(x)))

ws.bykid.longform <- melt(ws.vocab.words,id.vars="id",
                       variable.name = "word",
                       value.name="produces")
ws.bykid.longform <- merge(ws.bykid.longform,ws.categories,
                           by.x="word",by.y="lemma") %>%
  arrange(id)

ws.scores <- ws.bykid.longform %>%
  group_by(id,category) %>%
  summarise(productive = sum(produces))
```

Load child-specific data
```{r}
admins <- as.data.frame(select(admin.table,data_id,child_id,age,source_id))
children <- as.data.frame(select(child.table,id,gender,mom_ed,birth_order))

child.data <- merge(children,admins,by.y="child_id",by.x = "id")
wg.word.data <- merge(child.data,wg.bykid.longform)
wg.child.scores <- merge(child.data,wg.scores)

ws.word.data <- merge(child.data,ws.bykid.longform)
ws.child.scores <- merge(child.data,ws.scores)
```

Compute crosstabs
```{r}
wg.age.gender.data <- wg.child.scores %>%
  gather(measure,score,c(receptive,productive)) %>%
  group_by(age,gender,measure) %>%
  summarise(
    mean = mean(score),
    ci.l = ci.low(score),
    ci.h = ci.high(score),
    n = n())

#Show WG table
wg.age.gender.data

ws.age.gender.data <- ws.child.scores %>%
  group_by(age,gender,category) %>%
  filter(age>= 16, age <= 30) %>%
  summarise(
    mean = mean(productive),
    ci.l = ci.low(productive),
    ci.h = ci.high(productive),
    n = n())

#Show WS table
ws.age.gender.data
```

Plot WG
```{r}
quartz(width=7,height=4)
ggplot(wg.age.gender.data, 
       aes(x=age, y=mean,colour=gender,linetype=measure,
           group=interaction(gender,measure)))+
  geom_pointrange(aes(ymin = mean-ci.l,
                      ymax = mean+ci.h),
                  size = .8,
                  show_guide = FALSE) +
  geom_line(size=1) +
  scale_x_continuous(breaks=seq(8,18,1),
                     name = "Age (months)")+
  scale_y_continuous(name = "Vocabulary Size (words)") +
  theme_bw(base_size=14) +
  scale_color_manual(values = c("#e41a1c","#377eb8"))
```

Plot WS
```{r}
quartz(width=6,height=4)
ggplot(ws.age.gender.data, 
       aes(x=age, y=mean,colour=gender,label=gender))+
  geom_pointrange(aes(ymin = mean-ci.l,
                      ymax = mean+ci.h),
                  size = .8,
                  show_guide = FALSE) +
  geom_line(size=1) +
  scale_x_continuous(breaks=seq(16,30,1),limits=c(16,30.5),
                     name = "Age (months)")+
  scale_y_continuous(name = "Vocabulary Size (words)",limits=c(0,680)) +
  theme_bw(base_size=14) +
  theme(legend.position="none") +
  geom_dl(method=list("last.qp",cex=1,hjust=-.5)) +
  scale_color_manual(values = c("#e41a1c","#377eb8"))
```