% By-SES Norms for Wordbank
% Dan Yurovsky
% `r as.character(format(Sys.Date(), format="%B %d, %Y"))`

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(message=FALSE, warning=FALSE, cache=TRUE)
```
Load required libraries
```{r, cache=FALSE}
rm(list=ls())

library(ggplot2)
library(dplyr)
library(tidyr)
library(RMySQL)
library(stringr)
library(magrittr)
library(pcaPP)
library(directlabels)

man.cols <- c("#e41a1c","#377eb8","#4daf4a",
              "#984ea3","#ff7f00","#a65628",
              "#f781bf","#999999") #Brewer Set1 without yellow
```

Pull in wordbank dat
```{r, cache=FALSE}
## OPEN DATABASE CONNECTION ##
wordbank <- src_mysql(dbname='wordbank',host="54.149.39.46",
                      user="wordbank",password="wordbank")

## NOW LOAD TABLES ##
source.table <- tbl(wordbank,"common_source")
admin.table <- tbl(wordbank,"common_administration")
child.table <- tbl(wordbank,"common_child")
momed.table <-  tbl(wordbank,"common_momed")
wordmapping.table <- tbl(wordbank,"common_wordmapping")
instruments.table <- tbl(wordbank,"common_instrumentsmap")
english.ws.table <- tbl(wordbank,"instruments_english_ws")
norwegian.ws.table <- tbl(wordbank,"instruments_norwegian_ws")
danish.ws.table <- tbl(wordbank,"instruments_danish_ws")

# Get administration info
admins <- admin.table %>%
  select(data_id,child_id,age,source_id) %>%
  rename(id = data_id, child.id = child_id, source.id = source_id) %>%
  as.data.frame

# Get demographic variables for each child
demos <- select(child.table,id,sex,momed_id,birth_order) %>%
  rename(child.id = id) %>%# Rename id fields 
  as.data.frame %>%
  group_by(child.id) %>%
  rename(birth.order=birth_order) %>%
  filter(!is.na(momed_id)) %>%
  as.data.frame

momed.data <- momed.table %>%
  as.data.frame %>%
  arrange(order) %>%
  mutate(level = factor(level,levels=level))

demos <- left_join(demos,momed.data,
                   by=c("momed_id" = "id")) %>%
  rename(mom.ed = level) %>%
  select(-order) %>%
  rowwise() %>%
  mutate(birth.order = if(is.na(birth.order)) "NA"
                          else if(birth.order == 1) "First Born"
                          else "Later Born")
        
# Join age and demographics together
child.data <- as.tbl(left_join(admins,demos))

# Set up mappings and instruments.
mapping <- as.data.frame(wordmapping.table)
instruments <- as.data.frame(instruments.table) %>%
  rename(instrument_id = id)
items <- left_join(mapping, instruments)
```

Extract data for each kid
```{r}
# Function for getting all of the data in wordbank 
# for a given language (kid x item).
get.language.data <- function(lang.table, lang.items, lang, child.data) {
  
  instrument.items <- lang.items %>% 
    filter(language == lang, form == 'WS') %>%
    select(item, type, category, lexical_category, definition) %>%
    mutate(item = str_replace(item, "\\.", "_")) # Fix _/. inconsistencies
  
  instrument.data <- as.data.frame(lang.table) %>%
    rename(id = basetable_ptr_id) %>% # Rename the id
    gather(item, value, -id) %>% # Arrange in longform
    mutate(item = str_replace(item, "item_", "")) # Strip off item_ 
  
  d <- left_join(instrument.data, instrument.items)
  d <- left_join(d, child.data)
}

#Get (kid x item) data for all languages.
d.english <- get.language.data(lang.table=english.ws.table, 
                               lang.items=items, 
                               lang="English",
                               child.data)

d.norwegian <- get.language.data(lang.table=norwegian.ws.table, 
                              lang.items=items, 
                              lang="Norwegian",
                              child.data)

# Norwegian data is loaded in funny -- NAs in wordform are actually 0s
d.norwegian[d.norwegian$type %in% c("word_form","word")
         & is.na(d.norwegian$value),]$value = ""


# Danish data is loaded in funny -- NAs in wordform are actually 0s
d.danish <- get.language.data(lang.table=danish.ws.table, 
                              lang.items=items, 
                              lang="Danish",
                              child.data)

# Danish data is loaded in funny -- NAs in wordform are actually 0s
d.danish[d.danish$type %in% c("word_form","word")
         & is.na(d.danish$value),]$value = ""

#Function for getting vocab size data.
language.vocab.sizes.mom.ed <- function(lang.data,lang) {
  d.vocab <- lang.data %>%
    filter(type == "word") %>%
    group_by(age,mom.ed,id) %>%
    summarise(vocab.sum = sum(value == "produces", na.rm=TRUE),
              vocab.mean = vocab.sum/length(value)) %>%
    mutate(language = lang)
  
  return(d.vocab)
}

# language.vocab.sizes.bo <- function(lang.data,lang) {
#   d.vocab <- lang.data %>%
#     filter(type == "word") %>%
#     group_by(age,birth.order,id) %>%
#     summarise(vocab.sum = sum(value == "produces", na.rm=TRUE),
#               vocab.mean = vocab.sum/length(value)) %>%
#     mutate(language = lang)
#   
#   return(d.vocab)
# }

eng.mom.ed.data <- language.vocab.sizes.mom.ed(d.english,"English")
norw.mom.ed.data <- language.vocab.sizes.mom.ed(d.norwegian,"Norwegian")
dan.mom.ed.data <- language.vocab.sizes.mom.ed(d.danish,"Danish")

#eng.bo.data <- language.vocab.sizes.bo(d.english,"English")
#span.bo.data <- language.vocab.sizes.bo(d.spanish,"Spanish")
#dan.bo.data <- language.vocab.sizes.bo(d.danish,"Danish")
```

Put together all data, plot
```{r,fig.height = 6,fig.width=9}
#all.mom.ed.data <- bind_rows(eng.mom.ed.data,span.mom.ed.data)
all.mom.ed.data <- bind_rows(norw.mom.ed.data,eng.mom.ed.data,
                             dan.mom.ed.data) %>%
  filter(!is.na(mom.ed),mom.ed != "None",mom.ed !="Primary")

#all.bo.data <- bind_rows(eng.bo.data,span.bo.data)
#all.bo.data <- bind_rows(all.bo.data,dan.bo.data) %>%
#  filter(!is.na(birth.order))


cut.by <- .25
cuts <- seq(0.0,1.0, by=cut.by)

mom.ed.ddd <- all.mom.ed.data %>% 
  filter(age > 15, age < 31, mom.ed != "NA") %>%
  group_by(language,age,mom.ed) %>%
  mutate(p = rank(vocab.mean)/length(vocab.mean),
         Quantile = cut(p, breaks=cuts, 
                 labels= c("First Quartile", "Second Quartile",
                           "Third Quartile", "Fourth Quartile")))
                   #cuts[2:length(cuts)]-cut.by/2))

# quartz(height=6,width=8)
ggplot(mom.ed.ddd, aes(x=age, y=vocab.mean,colour=mom.ed))+
  geom_jitter(size = 1,position = position_jitter(.1), pch = "o") +
  geom_smooth(se=FALSE,span = 1,method="loess")+
  facet_grid(language ~ Quantile)+
  scale_x_continuous(breaks=seq(16,30,2),
                     limits=c(16,30.5),
                     name = "Age (months)")+
  scale_y_continuous(name = "Prop. Words Known") +
  scale_color_manual(values=man.cols,
                     guide = guide_legend(title = "Mother's Education",
                                          direction = "horizontal"))+
  theme_bw(base_size=12)+
  theme(legend.text=element_text(size=8),
        legend.title=element_text(size=8),
        legend.position=c(.4,.96))
```
```{r,fig.height = 6,fig.width=9}
ggplot(mom.ed.ddd, aes(x=age, y=vocab.mean,colour=language))+
  geom_jitter(size = 1,position = position_jitter(.1), pch = "o") +
  geom_smooth(se=FALSE,span = 1,method="loess")+
  facet_grid(mom.ed ~ Quantile)+
  scale_x_continuous(breaks=seq(16,30,2),
                     limits=c(16,30.5),
                     name = "Age (months)")+
  scale_y_continuous(name = "Prop. Words Known") +
  scale_color_manual(values=man.cols,
                     guide = guide_legend(title = "Language",
                                          direction = "horizontal"))+
  theme_bw(base_size=12)+
  theme(legend.text=element_text(size=8),
        legend.title=element_text(size=8),
        legend.position=c(.4,.96))

# 
# bo.ddd <- all.bo.data %>% 

# bo.ddd <- all.bo.data %>% 
#   filter(age > 15, age < 31, birth.order != "NA") %>%
#   group_by(language,age,birth.order) %>%
#   mutate(p = rank(vocab.mean)/length(vocab.mean),
#          Quantile = cut(p, breaks=cuts, 
#                  labels= c("First Quartile", "Second Quartile",
#                            "Third Quartile", "Fourth Quartile")))
#                    #cuts[2:length(cuts)]-cut.by/2))
# 
# #quartz(height=6,width=10)
# ggplot(bo.ddd, aes(x=age, y=vocab.mean,colour=birth.order))+
#   geom_jitter(size = .8,position = position_jitter(.1)) +
#   geom_smooth(se=FALSE,span = 1,method="loess")+
#   facet_grid(language ~ Quantile)+
#   scale_x_continuous(breaks=seq(16,30,2),
#                      limits=c(16,30.5),
#                      name = "Age (months)")+
#   scale_y_continuous(name = "Prop. Words Known") +
#   scale_color_manual(values=man.cols,
#                      guide = guide_legend(reverse = TRUE,
#                                           title = "Birth Order"))+
#   theme_bw(base_size=13)
```
