map_hash_bucket_size 128;

map $host $valid_host {
    "wordbank.stanford.edu"                                              1;
    "www.wordbank.stanford.edu"                                          1;
    "wordbank-dev.gsffhcf4an.us-west-2.elasticbeanstalk.com"             1;
    "wordbank-prod.gsffhcf4an.us-west-2.elasticbeanstalk.com"            1;
    "awseb--awseb-qvogu0bcjxkb-757196002.us-west-2.elb.amazonaws.com"    1;
    default                                                              0;
}
